/*
Magical Playlist Sorter API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package faelist.com/sorterv1

import (
	"encoding/json"
)

// checks if the PlaylistsPostIDParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaylistsPostIDParameter{}

// PlaylistsPostIDParameter struct for PlaylistsPostIDParameter
type PlaylistsPostIDParameter struct {
	SpotPlaylistID *string `json:"SpotPlaylistID,omitempty"`
	ApplSongID *int32 `json:"ApplSongID,omitempty"`
	YTMSongID *string `json:"YTMSongID,omitempty"`
}

// NewPlaylistsPostIDParameter instantiates a new PlaylistsPostIDParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaylistsPostIDParameter() *PlaylistsPostIDParameter {
	this := PlaylistsPostIDParameter{}
	return &this
}

// NewPlaylistsPostIDParameterWithDefaults instantiates a new PlaylistsPostIDParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaylistsPostIDParameterWithDefaults() *PlaylistsPostIDParameter {
	this := PlaylistsPostIDParameter{}
	return &this
}

// GetSpotPlaylistID returns the SpotPlaylistID field value if set, zero value otherwise.
func (o *PlaylistsPostIDParameter) GetSpotPlaylistID() string {
	if o == nil || IsNil(o.SpotPlaylistID) {
		var ret string
		return ret
	}
	return *o.SpotPlaylistID
}

// GetSpotPlaylistIDOk returns a tuple with the SpotPlaylistID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistsPostIDParameter) GetSpotPlaylistIDOk() (*string, bool) {
	if o == nil || IsNil(o.SpotPlaylistID) {
		return nil, false
	}
	return o.SpotPlaylistID, true
}

// HasSpotPlaylistID returns a boolean if a field has been set.
func (o *PlaylistsPostIDParameter) HasSpotPlaylistID() bool {
	if o != nil && !IsNil(o.SpotPlaylistID) {
		return true
	}

	return false
}

// SetSpotPlaylistID gets a reference to the given string and assigns it to the SpotPlaylistID field.
func (o *PlaylistsPostIDParameter) SetSpotPlaylistID(v string) {
	o.SpotPlaylistID = &v
}

// GetApplSongID returns the ApplSongID field value if set, zero value otherwise.
func (o *PlaylistsPostIDParameter) GetApplSongID() int32 {
	if o == nil || IsNil(o.ApplSongID) {
		var ret int32
		return ret
	}
	return *o.ApplSongID
}

// GetApplSongIDOk returns a tuple with the ApplSongID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistsPostIDParameter) GetApplSongIDOk() (*int32, bool) {
	if o == nil || IsNil(o.ApplSongID) {
		return nil, false
	}
	return o.ApplSongID, true
}

// HasApplSongID returns a boolean if a field has been set.
func (o *PlaylistsPostIDParameter) HasApplSongID() bool {
	if o != nil && !IsNil(o.ApplSongID) {
		return true
	}

	return false
}

// SetApplSongID gets a reference to the given int32 and assigns it to the ApplSongID field.
func (o *PlaylistsPostIDParameter) SetApplSongID(v int32) {
	o.ApplSongID = &v
}

// GetYTMSongID returns the YTMSongID field value if set, zero value otherwise.
func (o *PlaylistsPostIDParameter) GetYTMSongID() string {
	if o == nil || IsNil(o.YTMSongID) {
		var ret string
		return ret
	}
	return *o.YTMSongID
}

// GetYTMSongIDOk returns a tuple with the YTMSongID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistsPostIDParameter) GetYTMSongIDOk() (*string, bool) {
	if o == nil || IsNil(o.YTMSongID) {
		return nil, false
	}
	return o.YTMSongID, true
}

// HasYTMSongID returns a boolean if a field has been set.
func (o *PlaylistsPostIDParameter) HasYTMSongID() bool {
	if o != nil && !IsNil(o.YTMSongID) {
		return true
	}

	return false
}

// SetYTMSongID gets a reference to the given string and assigns it to the YTMSongID field.
func (o *PlaylistsPostIDParameter) SetYTMSongID(v string) {
	o.YTMSongID = &v
}

func (o PlaylistsPostIDParameter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaylistsPostIDParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SpotPlaylistID) {
		toSerialize["SpotPlaylistID"] = o.SpotPlaylistID
	}
	if !IsNil(o.ApplSongID) {
		toSerialize["ApplSongID"] = o.ApplSongID
	}
	if !IsNil(o.YTMSongID) {
		toSerialize["YTMSongID"] = o.YTMSongID
	}
	return toSerialize, nil
}

type NullablePlaylistsPostIDParameter struct {
	value *PlaylistsPostIDParameter
	isSet bool
}

func (v NullablePlaylistsPostIDParameter) Get() *PlaylistsPostIDParameter {
	return v.value
}

func (v *NullablePlaylistsPostIDParameter) Set(val *PlaylistsPostIDParameter) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaylistsPostIDParameter) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaylistsPostIDParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaylistsPostIDParameter(val *PlaylistsPostIDParameter) *NullablePlaylistsPostIDParameter {
	return &NullablePlaylistsPostIDParameter{value: val, isSet: true}
}

func (v NullablePlaylistsPostIDParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaylistsPostIDParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


